apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  labels:
    app: authservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice

    spec:
      containers:
        - name: authservice
          image: timnuwa/authservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: authservice-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: authservice-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: authservice-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: authservice-db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "8085"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authservice-secrets
                  key: mysql-root-password